---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: starwars-api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: starwars-api
    spec:
      containers:
        - name: starwars-api
          image: jamalyusuff/starwars-api
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_URLS
              value: http://*:80
  selector:
    matchLabels:
      app: starwars-api
---
apiVersion: v1
kind: Service
metadata:
  name: starwars-api
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: starwars-api
