---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: starwars-ui
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: starwars-ui
    spec:
      containers:
        - name: starwars-ui
          image: jamalyusuff/starwars-ui:latest
          ports:
            - containerPort: 3000
          env:
            - name: NEXT_PUBLIC_API_URL
              value: http://starwars-api
            # - name:
  selector:
    matchLabels:
      app: starwars-ui
---
apiVersion: v1
kind: Service
metadata:
  name: starwars-ui
spec:
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app: starwars-ui
